### ISSUE TITLE
LAN play not available

### ISSUE THREAD

**Issue by TimTheEnchanter95** [SirOMGitsYOU/VicariousNetwork#3]
It was figured out via help from the discord but when the "fabric proxy" mod is enabled I was not able to play on a LAN network with someone in my house. To solve it I disabled the mod using the enable/disable mods feature in the AT launcher. Didnt test if I only needed to disable on either the host or person joining, since I just disabled it on both right off the bat. Sibling was able to join afterward.

**Comment by SirOMGitsYOU** [comment]
As we have identified a very simple issue a fix has been pushed already for ATLauncher and one should be coming this evening for Curseforge

**Comment by SirOMGitsYOU** [comment]
This should have been resolved
