### ISSUE TITLE
Game crashes when I try to make a world

### ISSUE THREAD

**Issue by ILikeToRuinPeoplesDay** [SirOMGitsYOU/VicariousNetwork#5]
**Describe the bug**
The game crashes, though because of vanillafix I can continue from the title screen. However because of when it crashes
I can not play the game, it crashes when I attempt to make a world.

Steps to reproduce the behaviour:
1. I installed some of the mods I like to use
2. I attempted to create a single player world

**Expected behaviour**
The world gets generated and I continue as you would normally expect.

**Screenshots**

**Logs**
[latest.log](https://github.com/SirOMGitsYOU/VicariousNetwork/files/6587333/latest.log)

**Crash Reports**
[crash-2021-06-02_16.39.19-client.txt](https://github.com/SirOMGitsYOU/VicariousNetwork/files/6587332/crash-2021-06-02_16.39.19-client.txt)

**Modpack (please complete the following information):**
 - OS: Windows 10
 - Java Version 1.12.2
 - Modpack Version: 3.9.2

**Additional context**

**Comment by SirOMGitsYOU** [comment]
Assign more ram to the game, you're running out of memory. also

>  installed some of the mods I like to use

if you're installing extra mods this isn't supported.

**Comment by ILikeToRuinPeoplesDay** [comment]
> Assign more ram to the game, you're running out of memory. also
> 
> > installed some of the mods I like to use
> 
> if you're installing extra mods this isn't supported.

Yea I found out it needed more memory, also the extra mods work just fine sooo.
